/********************************************************************************
** Form generated from reading UI file 'syszuxpinyin.ui'
**
** Created by: Qt User Interface Compiler version 5.10.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SYSZUXPINYIN_H
#define UI_SYSZUXPINYIN_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>

QT_BEGIN_NAMESPACE

class Ui_Dialog
{
public:
    QPushButton *pushButton_u;
    QPushButton *pushButton_t;
    QPushButton *pushButton_y;
    QPushButton *pushButton_i;
    QPushButton *pushButton_q;
    QPushButton *pushButton_zuokuo;
    QPushButton *pushButton_p;
    QPushButton *pushButton_r;
    QPushButton *pushButton_youkuo;
    QPushButton *pushButton_w;
    QPushButton *pushButton_o;
    QPushButton *pushButton_e;
    QPushButton *pushButton_j;
    QPushButton *pushButton_g;
    QPushButton *pushButton_h;
    QPushButton *pushButton_k;
    QPushButton *pushButton_a;
    QPushButton *pushButton_quote;
    QPushButton *pushButton_semicolon;
    QPushButton *pushButton_f;
    QPushButton *pushButton_enter;
    QPushButton *pushButton_s;
    QPushButton *pushButton_l;
    QPushButton *pushButton_d;
    QPushButton *pushButton_m;
    QPushButton *pushButton_b;
    QPushButton *pushButton_n;
    QPushButton *pushButton_comma;
    QPushButton *pushButton_z;
    QPushButton *pushButton_splash;
    QPushButton *pushButton_v;
    QPushButton *pushButton_x;
    QPushButton *pushButton_period;
    QPushButton *pushButton_c;
    QPushButton *pushButton_shift;
    QPushButton *pushButton_whitespace;
    QPushButton *pushButton_up;
    QPushButton *pushButton_backsplash;
    QPushButton *pushButton_left;
    QPushButton *pushButton_right;
    QPushButton *pushButton_down;
    QPushButton *pushButton_n2;
    QPushButton *pushButton_is_hanzi;
    QPushButton *pushButton_ok;
    QPushButton *pushButton_hanzi_7;
    QPushButton *pushButton_hanzi_5;
    QPushButton *pushButton_hanzi_6;
    QPushButton *pushButton_hanzi_8;
    QPushButton *pushButton_hanzi_4;
    QPushButton *pushButton_hanzi_2;
    QPushButton *pushButton_hanzi_3;
    QPushButton *pushButton_hanzi_left;
    QPushButton *pushButton_hanzi_right;
    QPushButton *pushButton_hanzi_1;
    QLineEdit *lineEdit_pinyin;
    QPushButton *pushButton_n3;
    QPushButton *pushButton_backspace;
    QPushButton *pushButton_n0;
    QPushButton *pushButton_n1;
    QPushButton *pushButton_n6;
    QPushButton *pushButton_deng;
    QPushButton *pushButton_gang;
    QPushButton *pushButton_n5;
    QPushButton *pushButton_n7;
    QPushButton *pushButton_n8;
    QPushButton *pushButton_n4;
    QPushButton *pushButton_n9;
    QLineEdit *lineEdit_window;
    QPushButton *pushButton_cancel;

    void setupUi(QDialog *Dialog)
    {
        if (Dialog->objectName().isEmpty())
            Dialog->setObjectName(QStringLiteral("Dialog"));
        Dialog->resize(800, 480);
        pushButton_u = new QPushButton(Dialog);
        pushButton_u->setObjectName(QStringLiteral("pushButton_u"));
        pushButton_u->setGeometry(QRect(384, 240, 45, 45));
        QFont font;
        font.setPointSize(20);
        font.setBold(true);
        font.setWeight(75);
        pushButton_u->setFont(font);
        pushButton_t = new QPushButton(Dialog);
        pushButton_t->setObjectName(QStringLiteral("pushButton_t"));
        pushButton_t->setGeometry(QRect(283, 240, 45, 45));
        pushButton_t->setFont(font);
        pushButton_y = new QPushButton(Dialog);
        pushButton_y->setObjectName(QStringLiteral("pushButton_y"));
        pushButton_y->setGeometry(QRect(333, 240, 45, 45));
        pushButton_y->setFont(font);
        pushButton_i = new QPushButton(Dialog);
        pushButton_i->setObjectName(QStringLiteral("pushButton_i"));
        pushButton_i->setGeometry(QRect(434, 240, 45, 45));
        pushButton_i->setFont(font);
        pushButton_q = new QPushButton(Dialog);
        pushButton_q->setObjectName(QStringLiteral("pushButton_q"));
        pushButton_q->setGeometry(QRect(81, 240, 45, 45));
        pushButton_q->setFont(font);
        pushButton_zuokuo = new QPushButton(Dialog);
        pushButton_zuokuo->setObjectName(QStringLiteral("pushButton_zuokuo"));
        pushButton_zuokuo->setGeometry(QRect(585, 240, 45, 45));
        pushButton_zuokuo->setFont(font);
        pushButton_p = new QPushButton(Dialog);
        pushButton_p->setObjectName(QStringLiteral("pushButton_p"));
        pushButton_p->setGeometry(QRect(535, 240, 45, 45));
        pushButton_p->setFont(font);
        pushButton_r = new QPushButton(Dialog);
        pushButton_r->setObjectName(QStringLiteral("pushButton_r"));
        pushButton_r->setGeometry(QRect(233, 240, 45, 45));
        pushButton_r->setFont(font);
        pushButton_youkuo = new QPushButton(Dialog);
        pushButton_youkuo->setObjectName(QStringLiteral("pushButton_youkuo"));
        pushButton_youkuo->setGeometry(QRect(636, 240, 45, 45));
        pushButton_youkuo->setFont(font);
        pushButton_w = new QPushButton(Dialog);
        pushButton_w->setObjectName(QStringLiteral("pushButton_w"));
        pushButton_w->setGeometry(QRect(132, 240, 45, 45));
        pushButton_w->setFont(font);
        pushButton_o = new QPushButton(Dialog);
        pushButton_o->setObjectName(QStringLiteral("pushButton_o"));
        pushButton_o->setGeometry(QRect(485, 240, 45, 45));
        pushButton_o->setFont(font);
        pushButton_e = new QPushButton(Dialog);
        pushButton_e->setObjectName(QStringLiteral("pushButton_e"));
        pushButton_e->setGeometry(QRect(182, 240, 45, 45));
        pushButton_e->setFont(font);
        pushButton_j = new QPushButton(Dialog);
        pushButton_j->setObjectName(QStringLiteral("pushButton_j"));
        pushButton_j->setGeometry(QRect(421, 300, 45, 45));
        pushButton_j->setFont(font);
        pushButton_g = new QPushButton(Dialog);
        pushButton_g->setObjectName(QStringLiteral("pushButton_g"));
        pushButton_g->setGeometry(QRect(320, 300, 45, 45));
        pushButton_g->setFont(font);
        pushButton_h = new QPushButton(Dialog);
        pushButton_h->setObjectName(QStringLiteral("pushButton_h"));
        pushButton_h->setGeometry(QRect(370, 300, 45, 45));
        pushButton_h->setFont(font);
        pushButton_k = new QPushButton(Dialog);
        pushButton_k->setObjectName(QStringLiteral("pushButton_k"));
        pushButton_k->setGeometry(QRect(471, 300, 45, 45));
        pushButton_k->setFont(font);
        pushButton_a = new QPushButton(Dialog);
        pushButton_a->setObjectName(QStringLiteral("pushButton_a"));
        pushButton_a->setGeometry(QRect(118, 300, 45, 45));
        pushButton_a->setFont(font);
        pushButton_quote = new QPushButton(Dialog);
        pushButton_quote->setObjectName(QStringLiteral("pushButton_quote"));
        pushButton_quote->setGeometry(QRect(622, 300, 45, 45));
        pushButton_quote->setFont(font);
        pushButton_semicolon = new QPushButton(Dialog);
        pushButton_semicolon->setObjectName(QStringLiteral("pushButton_semicolon"));
        pushButton_semicolon->setGeometry(QRect(572, 300, 45, 45));
        pushButton_semicolon->setFont(font);
        pushButton_f = new QPushButton(Dialog);
        pushButton_f->setObjectName(QStringLiteral("pushButton_f"));
        pushButton_f->setGeometry(QRect(270, 300, 45, 45));
        pushButton_f->setFont(font);
        pushButton_enter = new QPushButton(Dialog);
        pushButton_enter->setObjectName(QStringLiteral("pushButton_enter"));
        pushButton_enter->setEnabled(false);
        pushButton_enter->setGeometry(QRect(10, 360, 100, 45));
        pushButton_enter->setFont(font);
        pushButton_s = new QPushButton(Dialog);
        pushButton_s->setObjectName(QStringLiteral("pushButton_s"));
        pushButton_s->setGeometry(QRect(169, 300, 45, 45));
        pushButton_s->setFont(font);
        pushButton_l = new QPushButton(Dialog);
        pushButton_l->setObjectName(QStringLiteral("pushButton_l"));
        pushButton_l->setGeometry(QRect(522, 300, 45, 45));
        pushButton_l->setFont(font);
        pushButton_d = new QPushButton(Dialog);
        pushButton_d->setObjectName(QStringLiteral("pushButton_d"));
        pushButton_d->setGeometry(QRect(219, 300, 45, 45));
        pushButton_d->setFont(font);
        pushButton_m = new QPushButton(Dialog);
        pushButton_m->setObjectName(QStringLiteral("pushButton_m"));
        pushButton_m->setGeometry(QRect(449, 360, 45, 45));
        pushButton_m->setFont(font);
        pushButton_b = new QPushButton(Dialog);
        pushButton_b->setObjectName(QStringLiteral("pushButton_b"));
        pushButton_b->setGeometry(QRect(348, 360, 45, 45));
        pushButton_b->setFont(font);
        pushButton_n = new QPushButton(Dialog);
        pushButton_n->setObjectName(QStringLiteral("pushButton_n"));
        pushButton_n->setGeometry(QRect(398, 360, 45, 45));
        pushButton_n->setFont(font);
        pushButton_comma = new QPushButton(Dialog);
        pushButton_comma->setObjectName(QStringLiteral("pushButton_comma"));
        pushButton_comma->setGeometry(QRect(499, 360, 45, 45));
        pushButton_comma->setFont(font);
        pushButton_z = new QPushButton(Dialog);
        pushButton_z->setObjectName(QStringLiteral("pushButton_z"));
        pushButton_z->setGeometry(QRect(146, 360, 45, 45));
        pushButton_z->setFont(font);
        pushButton_splash = new QPushButton(Dialog);
        pushButton_splash->setObjectName(QStringLiteral("pushButton_splash"));
        pushButton_splash->setGeometry(QRect(600, 360, 45, 45));
        pushButton_splash->setFont(font);
        pushButton_v = new QPushButton(Dialog);
        pushButton_v->setObjectName(QStringLiteral("pushButton_v"));
        pushButton_v->setGeometry(QRect(298, 360, 45, 45));
        pushButton_v->setFont(font);
        pushButton_x = new QPushButton(Dialog);
        pushButton_x->setObjectName(QStringLiteral("pushButton_x"));
        pushButton_x->setGeometry(QRect(197, 360, 45, 45));
        pushButton_x->setFont(font);
        pushButton_period = new QPushButton(Dialog);
        pushButton_period->setObjectName(QStringLiteral("pushButton_period"));
        pushButton_period->setGeometry(QRect(550, 360, 45, 45));
        pushButton_period->setFont(font);
        pushButton_c = new QPushButton(Dialog);
        pushButton_c->setObjectName(QStringLiteral("pushButton_c"));
        pushButton_c->setGeometry(QRect(247, 360, 45, 45));
        pushButton_c->setFont(font);
        pushButton_shift = new QPushButton(Dialog);
        pushButton_shift->setObjectName(QStringLiteral("pushButton_shift"));
        pushButton_shift->setGeometry(QRect(130, 420, 61, 45));
        pushButton_shift->setFont(font);
        pushButton_whitespace = new QPushButton(Dialog);
        pushButton_whitespace->setObjectName(QStringLiteral("pushButton_whitespace"));
        pushButton_whitespace->setGeometry(QRect(203, 419, 210, 45));
        pushButton_whitespace->setFont(font);
        pushButton_up = new QPushButton(Dialog);
        pushButton_up->setObjectName(QStringLiteral("pushButton_up"));
        pushButton_up->setEnabled(false);
        pushButton_up->setGeometry(QRect(720, 360, 60, 45));
        pushButton_up->setFont(font);
        pushButton_backsplash = new QPushButton(Dialog);
        pushButton_backsplash->setObjectName(QStringLiteral("pushButton_backsplash"));
        pushButton_backsplash->setGeometry(QRect(690, 240, 45, 45));
        pushButton_backsplash->setFont(font);
        pushButton_left = new QPushButton(Dialog);
        pushButton_left->setObjectName(QStringLiteral("pushButton_left"));
        pushButton_left->setEnabled(false);
        pushButton_left->setGeometry(QRect(720, 300, 60, 45));
        pushButton_left->setFont(font);
        pushButton_right = new QPushButton(Dialog);
        pushButton_right->setObjectName(QStringLiteral("pushButton_right"));
        pushButton_right->setEnabled(false);
        pushButton_right->setGeometry(QRect(730, 420, 60, 45));
        pushButton_right->setFont(font);
        pushButton_down = new QPushButton(Dialog);
        pushButton_down->setObjectName(QStringLiteral("pushButton_down"));
        pushButton_down->setEnabled(false);
        pushButton_down->setGeometry(QRect(30, 420, 60, 45));
        pushButton_down->setFont(font);
        pushButton_n2 = new QPushButton(Dialog);
        pushButton_n2->setObjectName(QStringLiteral("pushButton_n2"));
        pushButton_n2->setGeometry(QRect(96, 180, 45, 45));
        pushButton_n2->setFont(font);
        pushButton_n2->setFocusPolicy(Qt::ClickFocus);
        pushButton_is_hanzi = new QPushButton(Dialog);
        pushButton_is_hanzi->setObjectName(QStringLiteral("pushButton_is_hanzi"));
        pushButton_is_hanzi->setGeometry(QRect(430, 420, 45, 45));
        QFont font1;
        font1.setPointSize(15);
        font1.setBold(true);
        font1.setWeight(75);
        pushButton_is_hanzi->setFont(font1);
        pushButton_ok = new QPushButton(Dialog);
        pushButton_ok->setObjectName(QStringLiteral("pushButton_ok"));
        pushButton_ok->setGeometry(QRect(580, 420, 91, 45));
        QPalette palette;
        QBrush brush(QColor(0, 255, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        QBrush brush1(QColor(118, 116, 108, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_ok->setPalette(palette);
        QFont font2;
        font2.setPointSize(24);
        font2.setBold(false);
        font2.setWeight(50);
        pushButton_ok->setFont(font2);
        pushButton_hanzi_7 = new QPushButton(Dialog);
        pushButton_hanzi_7->setObjectName(QStringLiteral("pushButton_hanzi_7"));
        pushButton_hanzi_7->setGeometry(QRect(471, 130, 45, 35));
        pushButton_hanzi_7->setFont(font1);
        pushButton_hanzi_5 = new QPushButton(Dialog);
        pushButton_hanzi_5->setObjectName(QStringLiteral("pushButton_hanzi_5"));
        pushButton_hanzi_5->setGeometry(QRect(370, 130, 45, 35));
        pushButton_hanzi_5->setFont(font1);
        pushButton_hanzi_6 = new QPushButton(Dialog);
        pushButton_hanzi_6->setObjectName(QStringLiteral("pushButton_hanzi_6"));
        pushButton_hanzi_6->setGeometry(QRect(420, 130, 45, 35));
        pushButton_hanzi_6->setFont(font1);
        pushButton_hanzi_8 = new QPushButton(Dialog);
        pushButton_hanzi_8->setObjectName(QStringLiteral("pushButton_hanzi_8"));
        pushButton_hanzi_8->setGeometry(QRect(521, 130, 45, 35));
        pushButton_hanzi_8->setFont(font1);
        pushButton_hanzi_4 = new QPushButton(Dialog);
        pushButton_hanzi_4->setObjectName(QStringLiteral("pushButton_hanzi_4"));
        pushButton_hanzi_4->setGeometry(QRect(320, 130, 45, 35));
        pushButton_hanzi_4->setFont(font1);
        pushButton_hanzi_2 = new QPushButton(Dialog);
        pushButton_hanzi_2->setObjectName(QStringLiteral("pushButton_hanzi_2"));
        pushButton_hanzi_2->setGeometry(QRect(219, 130, 45, 35));
        pushButton_hanzi_2->setFont(font1);
        pushButton_hanzi_3 = new QPushButton(Dialog);
        pushButton_hanzi_3->setObjectName(QStringLiteral("pushButton_hanzi_3"));
        pushButton_hanzi_3->setGeometry(QRect(269, 130, 45, 35));
        pushButton_hanzi_3->setFont(font1);
        pushButton_hanzi_left = new QPushButton(Dialog);
        pushButton_hanzi_left->setObjectName(QStringLiteral("pushButton_hanzi_left"));
        pushButton_hanzi_left->setGeometry(QRect(96, 130, 70, 35));
        pushButton_hanzi_left->setFont(font);
        pushButton_hanzi_right = new QPushButton(Dialog);
        pushButton_hanzi_right->setObjectName(QStringLiteral("pushButton_hanzi_right"));
        pushButton_hanzi_right->setGeometry(QRect(569, 130, 70, 35));
        pushButton_hanzi_right->setFont(font);
        pushButton_hanzi_1 = new QPushButton(Dialog);
        pushButton_hanzi_1->setObjectName(QStringLiteral("pushButton_hanzi_1"));
        pushButton_hanzi_1->setGeometry(QRect(169, 130, 45, 35));
        pushButton_hanzi_1->setFont(font1);
        lineEdit_pinyin = new QLineEdit(Dialog);
        lineEdit_pinyin->setObjectName(QStringLiteral("lineEdit_pinyin"));
        lineEdit_pinyin->setGeometry(QRect(650, 130, 141, 35));
        QFont font3;
        font3.setFamily(QString::fromUtf8("\345\276\256\350\275\257\351\233\205\351\273\221"));
        font3.setPointSize(21);
        font3.setBold(true);
        font3.setWeight(75);
        lineEdit_pinyin->setFont(font3);
        lineEdit_pinyin->setFrame(false);
        pushButton_n3 = new QPushButton(Dialog);
        pushButton_n3->setObjectName(QStringLiteral("pushButton_n3"));
        pushButton_n3->setGeometry(QRect(146, 180, 45, 45));
        pushButton_n3->setFont(font);
        pushButton_backspace = new QPushButton(Dialog);
        pushButton_backspace->setObjectName(QStringLiteral("pushButton_backspace"));
        pushButton_backspace->setGeometry(QRect(650, 180, 121, 45));
        QFont font4;
        font4.setPointSize(10);
        font4.setBold(true);
        font4.setWeight(75);
        pushButton_backspace->setFont(font4);
        pushButton_n0 = new QPushButton(Dialog);
        pushButton_n0->setObjectName(QStringLiteral("pushButton_n0"));
        pushButton_n0->setGeometry(QRect(499, 180, 45, 45));
        pushButton_n0->setFont(font);
        pushButton_n1 = new QPushButton(Dialog);
        pushButton_n1->setObjectName(QStringLiteral("pushButton_n1"));
        pushButton_n1->setGeometry(QRect(45, 180, 45, 45));
        pushButton_n1->setFont(font);
        pushButton_n1->setFocusPolicy(Qt::ClickFocus);
        pushButton_n6 = new QPushButton(Dialog);
        pushButton_n6->setObjectName(QStringLiteral("pushButton_n6"));
        pushButton_n6->setGeometry(QRect(297, 180, 45, 45));
        pushButton_n6->setFont(font);
        pushButton_deng = new QPushButton(Dialog);
        pushButton_deng->setObjectName(QStringLiteral("pushButton_deng"));
        pushButton_deng->setGeometry(QRect(600, 180, 45, 45));
        pushButton_deng->setFont(font);
        pushButton_gang = new QPushButton(Dialog);
        pushButton_gang->setObjectName(QStringLiteral("pushButton_gang"));
        pushButton_gang->setGeometry(QRect(549, 180, 45, 45));
        pushButton_gang->setFont(font);
        pushButton_n5 = new QPushButton(Dialog);
        pushButton_n5->setObjectName(QStringLiteral("pushButton_n5"));
        pushButton_n5->setGeometry(QRect(247, 180, 45, 45));
        pushButton_n5->setFont(font);
        pushButton_n7 = new QPushButton(Dialog);
        pushButton_n7->setObjectName(QStringLiteral("pushButton_n7"));
        pushButton_n7->setGeometry(QRect(348, 180, 45, 45));
        pushButton_n7->setFont(font);
        pushButton_n8 = new QPushButton(Dialog);
        pushButton_n8->setObjectName(QStringLiteral("pushButton_n8"));
        pushButton_n8->setGeometry(QRect(398, 180, 45, 45));
        pushButton_n8->setFont(font);
        pushButton_n4 = new QPushButton(Dialog);
        pushButton_n4->setObjectName(QStringLiteral("pushButton_n4"));
        pushButton_n4->setGeometry(QRect(197, 180, 45, 45));
        pushButton_n4->setFont(font);
        pushButton_n9 = new QPushButton(Dialog);
        pushButton_n9->setObjectName(QStringLiteral("pushButton_n9"));
        pushButton_n9->setGeometry(QRect(449, 180, 45, 45));
        pushButton_n9->setFont(font);
        lineEdit_window = new QLineEdit(Dialog);
        lineEdit_window->setObjectName(QStringLiteral("lineEdit_window"));
        lineEdit_window->setGeometry(QRect(10, 20, 781, 91));
        QFont font5;
        font5.setPointSize(20);
        lineEdit_window->setFont(font5);
        pushButton_cancel = new QPushButton(Dialog);
        pushButton_cancel->setObjectName(QStringLiteral("pushButton_cancel"));
        pushButton_cancel->setGeometry(QRect(480, 420, 91, 45));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_cancel->setPalette(palette1);
        pushButton_cancel->setFont(font2);
        QWidget::setTabOrder(pushButton_hanzi_left, pushButton_hanzi_1);
        QWidget::setTabOrder(pushButton_hanzi_1, pushButton_hanzi_2);
        QWidget::setTabOrder(pushButton_hanzi_2, pushButton_hanzi_3);
        QWidget::setTabOrder(pushButton_hanzi_3, pushButton_hanzi_4);
        QWidget::setTabOrder(pushButton_hanzi_4, pushButton_hanzi_5);
        QWidget::setTabOrder(pushButton_hanzi_5, pushButton_hanzi_6);
        QWidget::setTabOrder(pushButton_hanzi_6, pushButton_hanzi_7);
        QWidget::setTabOrder(pushButton_hanzi_7, pushButton_hanzi_8);
        QWidget::setTabOrder(pushButton_hanzi_8, pushButton_hanzi_right);
        QWidget::setTabOrder(pushButton_hanzi_right, pushButton_n1);
        QWidget::setTabOrder(pushButton_n1, pushButton_n2);
        QWidget::setTabOrder(pushButton_n2, pushButton_n3);
        QWidget::setTabOrder(pushButton_n3, pushButton_n4);
        QWidget::setTabOrder(pushButton_n4, pushButton_n5);
        QWidget::setTabOrder(pushButton_n5, pushButton_n6);
        QWidget::setTabOrder(pushButton_n6, pushButton_n7);
        QWidget::setTabOrder(pushButton_n7, pushButton_n8);
        QWidget::setTabOrder(pushButton_n8, pushButton_n9);
        QWidget::setTabOrder(pushButton_n9, pushButton_n0);
        QWidget::setTabOrder(pushButton_n0, pushButton_gang);
        QWidget::setTabOrder(pushButton_gang, pushButton_deng);
        QWidget::setTabOrder(pushButton_deng, pushButton_backspace);
        QWidget::setTabOrder(pushButton_backspace, pushButton_q);
        QWidget::setTabOrder(pushButton_q, pushButton_w);
        QWidget::setTabOrder(pushButton_w, pushButton_e);
        QWidget::setTabOrder(pushButton_e, pushButton_r);
        QWidget::setTabOrder(pushButton_r, pushButton_t);
        QWidget::setTabOrder(pushButton_t, pushButton_y);
        QWidget::setTabOrder(pushButton_y, pushButton_u);
        QWidget::setTabOrder(pushButton_u, pushButton_i);
        QWidget::setTabOrder(pushButton_i, pushButton_o);
        QWidget::setTabOrder(pushButton_o, pushButton_p);
        QWidget::setTabOrder(pushButton_p, pushButton_zuokuo);
        QWidget::setTabOrder(pushButton_zuokuo, pushButton_youkuo);
        QWidget::setTabOrder(pushButton_youkuo, pushButton_backsplash);
        QWidget::setTabOrder(pushButton_backsplash, pushButton_a);
        QWidget::setTabOrder(pushButton_a, pushButton_s);
        QWidget::setTabOrder(pushButton_s, pushButton_d);
        QWidget::setTabOrder(pushButton_d, pushButton_f);
        QWidget::setTabOrder(pushButton_f, pushButton_g);
        QWidget::setTabOrder(pushButton_g, pushButton_h);
        QWidget::setTabOrder(pushButton_h, pushButton_j);
        QWidget::setTabOrder(pushButton_j, pushButton_k);
        QWidget::setTabOrder(pushButton_k, pushButton_l);
        QWidget::setTabOrder(pushButton_l, pushButton_semicolon);
        QWidget::setTabOrder(pushButton_semicolon, pushButton_quote);
        QWidget::setTabOrder(pushButton_quote, pushButton_enter);
        QWidget::setTabOrder(pushButton_enter, pushButton_z);
        QWidget::setTabOrder(pushButton_z, pushButton_x);
        QWidget::setTabOrder(pushButton_x, pushButton_c);
        QWidget::setTabOrder(pushButton_c, pushButton_v);
        QWidget::setTabOrder(pushButton_v, pushButton_b);
        QWidget::setTabOrder(pushButton_b, pushButton_n);
        QWidget::setTabOrder(pushButton_n, pushButton_m);
        QWidget::setTabOrder(pushButton_m, pushButton_comma);
        QWidget::setTabOrder(pushButton_comma, pushButton_period);
        QWidget::setTabOrder(pushButton_period, pushButton_splash);
        QWidget::setTabOrder(pushButton_splash, pushButton_shift);
        QWidget::setTabOrder(pushButton_shift, pushButton_whitespace);
        QWidget::setTabOrder(pushButton_whitespace, pushButton_is_hanzi);
        QWidget::setTabOrder(pushButton_is_hanzi, pushButton_ok);
        QWidget::setTabOrder(pushButton_ok, pushButton_left);
        QWidget::setTabOrder(pushButton_left, pushButton_down);
        QWidget::setTabOrder(pushButton_down, pushButton_right);
        QWidget::setTabOrder(pushButton_right, pushButton_up);
        QWidget::setTabOrder(pushButton_up, lineEdit_pinyin);

        retranslateUi(Dialog);

        QMetaObject::connectSlotsByName(Dialog);
    } // setupUi

    void retranslateUi(QDialog *Dialog)
    {
        Dialog->setWindowTitle(QApplication::translate("Dialog", "Dialog", nullptr));
        pushButton_u->setText(QApplication::translate("Dialog", "u", nullptr));
        pushButton_t->setText(QApplication::translate("Dialog", "t", nullptr));
        pushButton_y->setText(QApplication::translate("Dialog", "y", nullptr));
        pushButton_i->setText(QApplication::translate("Dialog", "i", nullptr));
        pushButton_q->setText(QApplication::translate("Dialog", "q", nullptr));
        pushButton_zuokuo->setText(QApplication::translate("Dialog", "[", nullptr));
        pushButton_p->setText(QApplication::translate("Dialog", "p", nullptr));
        pushButton_r->setText(QApplication::translate("Dialog", "r", nullptr));
        pushButton_youkuo->setText(QApplication::translate("Dialog", "]", nullptr));
        pushButton_w->setText(QApplication::translate("Dialog", "w", nullptr));
        pushButton_o->setText(QApplication::translate("Dialog", "o", nullptr));
        pushButton_e->setText(QApplication::translate("Dialog", "e", nullptr));
        pushButton_j->setText(QApplication::translate("Dialog", "j", nullptr));
        pushButton_g->setText(QApplication::translate("Dialog", "g", nullptr));
        pushButton_h->setText(QApplication::translate("Dialog", "h", nullptr));
        pushButton_k->setText(QApplication::translate("Dialog", "k", nullptr));
        pushButton_a->setText(QApplication::translate("Dialog", "a", nullptr));
        pushButton_quote->setText(QApplication::translate("Dialog", "'", nullptr));
        pushButton_semicolon->setText(QApplication::translate("Dialog", ";", nullptr));
        pushButton_f->setText(QApplication::translate("Dialog", "f", nullptr));
        pushButton_enter->setText(QApplication::translate("Dialog", "enter", nullptr));
        pushButton_s->setText(QApplication::translate("Dialog", "s", nullptr));
        pushButton_l->setText(QApplication::translate("Dialog", "l", nullptr));
        pushButton_d->setText(QApplication::translate("Dialog", "d", nullptr));
        pushButton_m->setText(QApplication::translate("Dialog", "m", nullptr));
        pushButton_b->setText(QApplication::translate("Dialog", "b", nullptr));
        pushButton_n->setText(QApplication::translate("Dialog", "n", nullptr));
        pushButton_comma->setText(QApplication::translate("Dialog", ",", nullptr));
        pushButton_z->setText(QApplication::translate("Dialog", "z", nullptr));
        pushButton_splash->setText(QApplication::translate("Dialog", "/", nullptr));
        pushButton_v->setText(QApplication::translate("Dialog", "v", nullptr));
        pushButton_x->setText(QApplication::translate("Dialog", "x", nullptr));
        pushButton_period->setText(QApplication::translate("Dialog", ".", nullptr));
        pushButton_c->setText(QApplication::translate("Dialog", "c", nullptr));
        pushButton_shift->setText(QApplication::translate("Dialog", "shift", nullptr));
        pushButton_whitespace->setText(QApplication::translate("Dialog", "whitespace", nullptr));
        pushButton_up->setText(QApplication::translate("Dialog", "\342\206\221", nullptr));
        pushButton_backsplash->setText(QApplication::translate("Dialog", "\\", nullptr));
        pushButton_left->setText(QApplication::translate("Dialog", "\342\206\220", nullptr));
        pushButton_right->setText(QApplication::translate("Dialog", "\342\206\222", nullptr));
        pushButton_down->setText(QApplication::translate("Dialog", "\342\206\223", nullptr));
        pushButton_n2->setText(QApplication::translate("Dialog", "2", nullptr));
        pushButton_is_hanzi->setText(QApplication::translate("Dialog", "\350\213\261", nullptr));
        pushButton_ok->setText(QApplication::translate("Dialog", "\347\241\256\345\256\232", nullptr));
        pushButton_hanzi_7->setText(QString());
        pushButton_hanzi_5->setText(QString());
        pushButton_hanzi_6->setText(QString());
        pushButton_hanzi_8->setText(QString());
        pushButton_hanzi_4->setText(QString());
        pushButton_hanzi_2->setText(QString());
        pushButton_hanzi_3->setText(QString());
        pushButton_hanzi_left->setText(QApplication::translate("Dialog", "\342\206\220", nullptr));
        pushButton_hanzi_right->setText(QApplication::translate("Dialog", "\342\206\222", nullptr));
        pushButton_hanzi_1->setText(QString());
        lineEdit_pinyin->setText(QString());
        pushButton_n3->setText(QApplication::translate("Dialog", "3", nullptr));
        pushButton_backspace->setText(QApplication::translate("Dialog", "backspace", nullptr));
        pushButton_n0->setText(QApplication::translate("Dialog", "0", nullptr));
        pushButton_n1->setText(QApplication::translate("Dialog", "1", nullptr));
        pushButton_n6->setText(QApplication::translate("Dialog", "6", nullptr));
        pushButton_deng->setText(QApplication::translate("Dialog", "=", nullptr));
        pushButton_gang->setText(QApplication::translate("Dialog", "-", nullptr));
        pushButton_n5->setText(QApplication::translate("Dialog", "5", nullptr));
        pushButton_n7->setText(QApplication::translate("Dialog", "7", nullptr));
        pushButton_n8->setText(QApplication::translate("Dialog", "8", nullptr));
        pushButton_n4->setText(QApplication::translate("Dialog", "4", nullptr));
        pushButton_n9->setText(QApplication::translate("Dialog", "9", nullptr));
        pushButton_cancel->setText(QApplication::translate("Dialog", "\345\217\226\346\266\210", nullptr));
    } // retranslateUi

};

namespace Ui {
    class Dialog: public Ui_Dialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SYSZUXPINYIN_H
